#!/usr/bin/env sh

# To setup the development environment

set -e

cp bash_profile ~/.bash_profile
cp agignore ~/.agignore
cp ctags ~/.ctags
#cp bash_profile ~/.bash_profile
cp vimrc ~/.vimrc
cp coc-setting.json ~/.vim/coc-settings.json

# Install homebrew
if ! brew -v  &> /dev/null
then
  curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh
fi

# Install softwares
brew install fzf the_silver_searcher macvim bash_completion yarn universal-ctags watchman wget readline rbenv ruby-build postgresql node

# Fetch git-completion.bash
curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash > ~/.git-completion.bash

#To install useful keybindings and fuzzy completion
/usr/local/opt/fzf/install

# Install latest Ruby
rbenv install $(rbenv install -l | grep -v - | tail -1)
rbenv rehash

# For ruby language server
gem install solargraph

# Install gem-ctags and run ctags to generate tags for each gems
gem install gem-ctags
gem ctags

# Switched to coc-nvim documentation function
# Generate ri documentation for pressing K in vim
#gem rdoc --ri --all --overwrite

# Switched to fzf.vim
#mkdir .vim/autoload/ctrlp
#cp vim/autoload/ctrlp/tag.vim .vim/autoload/ctrlp/tag.vim

# Install vim-plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Install plugins and install coc extension in vim
vim -S snapshot.vim -c 'CocInstall -sync coc-snippets coc-tag coc-json coc-pairs coc-syntax coc-css coc-html coc-solargraph coc-tsserver coc-translator coc-sh coc-yank'
#vim -c 'CocInstall -sync coc-snippets coc-tag coc-json coc-pairs coc-syntax coc-css coc-html coc-solargraph coc-tsserver coc-translator coc-sh coc-yank|q'
